# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fourierin_1d_cpp <- function(f, a, b, c, d, r, s) {
    .Call('_solefinder_fourierin_1d_cpp', PACKAGE = 'solefinder', f, a, b, c, d, r, s)
}

fourierin_1d_nonregular_cpp <- function(f, a, b, w, resolution, r, s) {
    .Call('_solefinder_fourierin_1d_nonregular_cpp', PACKAGE = 'solefinder', f, a, b, w, resolution, r, s)
}

